// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeAyuDeneme.Data;

#nullable disable

namespace ProjeAyuDeneme.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023181217_AddOnayDurumuToFaaliyetler")]
    partial class AddOnayDurumuToFaaliyetler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Agirlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Kapsam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Agirlamalar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Pozisyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OfisId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Fuar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Degerlendirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etkinlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuarAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatilimSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Odul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("StandM2")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Statu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Fuarlar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.GenelButce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaslangicTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GenelButceler");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.KulturSanat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Etkinlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kisi")
                        .HasColumnType("int");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mekan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("KulturSanatlar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Mahsup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OdenekId")
                        .HasColumnType("int");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OdenekId");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Mahsuplar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Odenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Odenekler");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Ofis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ofisler");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Reklam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mecra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Reklamlar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Sektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degeri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kriter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mecra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfisId")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tertip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.HasIndex("UserId");

                    b.ToTable("Sektorler");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Agirlama", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Agirlamalar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.ApplicationUser", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ofis");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Fuar", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Fuarlar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.KulturSanat", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("KulturSanatlar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Mahsup", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Odenek", "Odenek")
                        .WithMany("Mahsuplar")
                        .HasForeignKey("OdenekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany("Mahsuplar")
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Mahsuplar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odenek");

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Odenek", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany("Odenekler")
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Odenekler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Reklam", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Reklamlar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Sektor", b =>
                {
                    b.HasOne("ProjeAyuDeneme.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjeAyuDeneme.Models.ApplicationUser", "User")
                        .WithMany("Sektorler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ofis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.ApplicationUser", b =>
                {
                    b.Navigation("Agirlamalar");

                    b.Navigation("Fuarlar");

                    b.Navigation("KulturSanatlar");

                    b.Navigation("Mahsuplar");

                    b.Navigation("Odenekler");

                    b.Navigation("Reklamlar");

                    b.Navigation("Sektorler");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Odenek", b =>
                {
                    b.Navigation("Mahsuplar");
                });

            modelBuilder.Entity("ProjeAyuDeneme.Models.Ofis", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Mahsuplar");

                    b.Navigation("Odenekler");
                });
#pragma warning restore 612, 618
        }
    }
}
